import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  foreign: [
    {
      type: 'autogenerated',
      dirName: '1-해외여행',
    },
  ],
  domestic: [
    {
      type: 'autogenerated',
      dirName: '2-국내여행',
    },
  ],
  diary: [
    {
      type: 'category',
      label: '연간회고',
      items: [
        '연간회고/2024',
      ],
    },
  ],
};

export default sidebars;
