import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  foreign: [
    {
      type: 'autogenerated',
      dirName: 'foreign',
    },
  ],
  domestic: [
    {
      type: 'autogenerated',
      dirName: 'domestic',
    },
  ],
};

export default sidebars;
