import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  foreign: [
    {
      type: 'autogenerated',
      dirName: '해외여행',
    },
  ],
  domestic: [
    {
      type: 'autogenerated',
      dirName: '국내여행',
    },
  ],
};

export default sidebars;
