name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main  # 메인 브랜치에서 변경이 발생할 때 빌드 및 배포

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18  # Docusaurus는 Node.js 14 이상을 권장

      - name: Install dependencies
        run: npm install

      - name: Build Docusaurus
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy
