name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main  # 메인 브랜치에서 변경이 발생할 때 빌드 및 배포

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Install dependencies
        run: npm install

      - name: Build Docusaurus
        run: npm run build
